import { ChangeDetectionStrategy, Component, ElementRef, ViewChild, inject, signal } from '@angular/core';
import { finalize } from 'rxjs';
import { AlgorithmExplanationComponent } from '../../components/algorithm-explanation/algorithm-explanation'; import { FuzzyHeaderComponent } from '../../components/fuzzy-header/fuzzy-header'; import { FuzzyMatchTableComponent } from '../../components/fuzzy-match-table/fuzzy-match-table'; import { MatchScoreCardsComponent } from '../../components/match-score-cards/match-score-cards'; import { MetricSpectrumComponent } from '../../components/metric-spectrum/metric-spectrum'; import { StringPairTesterComponent } from '../../components/string-pair-tester/string-pair-tester';
import { FuzzyMatchRecord } from '../../models/fuzzy-match-record.model'; import { FuzzyMatchResult } from '../../models/fuzzy-match-result.model'; import { FuzzyMatchService } from '../../services/fuzzy-match.service';
const INITIAL_RESULT: FuzzyMatchResult = { jaroWinklerScore: 91, levenshteinScore: 72, tokenSortScore: 72, soundexMaster: 'R522', soundexScheme: 'R522', phoneticMatch: true, finalScore: 81.5, threshold: 75, status: 'MATCHED' };
@Component({ selector: 'app-fuzzy-match-lab', standalone: true, imports: [FuzzyHeaderComponent, StringPairTesterComponent, MatchScoreCardsComponent, MetricSpectrumComponent, AlgorithmExplanationComponent, FuzzyMatchTableComponent], templateUrl: './fuzzy-match-lab.html', styleUrl: './fuzzy-match-lab.css', changeDetection: ChangeDetectionStrategy.OnPush })
export class FuzzyMatchLabPage {
  private readonly service = inject(FuzzyMatchService); @ViewChild('tester') private tester?: ElementRef<HTMLElement>;
  readonly masterName = signal('RAMESH KUMAR SAHOO'); readonly schemeName = signal('RAMESH KU SAHU'); readonly threshold = signal(75); readonly result = signal<FuzzyMatchResult>(INITIAL_RESULT); readonly records = signal<FuzzyMatchRecord[]>([]); readonly loading = signal(true); readonly regenerating = signal(false); readonly error = signal<string | null>(null);
  constructor() { this.loadRecords(); }
  setNames(names: { masterName: string; schemeName: string }): void { this.masterName.set(names.masterName); this.schemeName.set(names.schemeName); }
  setThreshold(value: number): void { this.threshold.set(value); this.result.update((result) => this.withStatus({ ...result, threshold: value })); }
  loadPreset(): void { this.masterName.set('RAMESH KUMAR SAHOO'); this.schemeName.set('RAMESH KU SAHU'); this.calculate(); }
  calculate(): void { this.error.set(null); this.service.calculateMatch({ masterName: this.masterName(), schemeName: this.schemeName(), threshold: this.threshold() }).subscribe({ next: (result) => this.result.set(this.withStatus(result)), error: () => this.error.set('Unable to calculate the fuzzy match. Please try again.') }); }
  selectRecord(record: FuzzyMatchRecord): void { this.masterName.set(record.masterName); this.schemeName.set(record.schemeName); this.calculate(); requestAnimationFrame(() => this.tester?.nativeElement.scrollIntoView({ behavior: 'smooth', block: 'start' })); }
  regenerate(): void { if (this.regenerating()) return; this.regenerating.set(true); this.error.set(null); this.service.regenerateEngineData().pipe(finalize(() => this.regenerating.set(false))).subscribe({ next: () => this.loadRecords(), error: () => this.error.set('Unable to regenerate engine data. Please try again.') }); }
  private loadRecords(): void { this.loading.set(true); this.service.getFuzzyMatchRecords().pipe(finalize(() => this.loading.set(false))).subscribe({ next: (records) => this.records.set(records), error: () => { this.records.set([]); this.error.set('Unable to load fuzzy match records.'); } }); }
  private withStatus(result: FuzzyMatchResult): FuzzyMatchResult { const status = result.finalScore >= result.threshold ? 'MATCHED' : result.finalScore >= result.threshold - 15 ? 'REVIEW_REQUIRED' : 'NOT_MATCHED'; return { ...result, status }; }
}
